import type { StrategyInput } from "../src/engine/strategy.js";
import type { MarketBriefInput } from "../src/engine/marketBrief.js";

/** Mirrors real-estate-exec-brief/examples/output-marketing-strategy-leadership.md (fictional figures). */
export const LK014: StrategyInput = {
  listing: {
    id: "LK-014",
    district: "Lekki Phase 1",
    type: "detached_duplex",
    bedrooms: 5,
    plot_sqm: 450,
    built_sqm: 520,
    title: "governors_consent",
    condition: "renovated",
    amenities: ["pool", "solar-inverter hybrid power", "24h estate security"],
    asking_price_ngn: 650_000_000,
    floor_price_ngn: 560_000_000,
  },
  transaction: "sale",
  comps: [
    { label: "C1", description: "5-bed detached, 450 sqm", status: "closed", date: "Aug 2026", price_ngn: 590_000_000, adjustments_pct: 5, adjustment_note: "dated finish", source: "Closed: internal" },
    { label: "C2", description: "5-bed detached, 500 sqm", status: "closed", date: "May 2026", price_ngn: 610_000_000, adjustments_pct: -5, adjustment_note: "larger plot", source: "Closed: agent-reported" },
    { label: "C3", description: "4-bed detached + BQ, 400 sqm", status: "closed", date: "Mar 2026", price_ngn: 520_000_000, adjustments_pct: 12, adjustment_note: "bedroom, smaller plot", source: "Closed: internal" },
    { label: "A1", description: "5-bed detached, 450 sqm", status: "asking", date: "Jul 2026", price_ngn: 680_000_000, days_listed: 80, source: "NPC asking" },
    { label: "A2", description: "5-bed detached, 600 sqm", status: "asking", date: "Jun 2026", price_ngn: 750_000_000, adjustments_pct: -15, adjustment_note: "larger plot", days_listed: 110, source: "NPC asking" },
    { label: "A3", description: "5-bed detached, 450 sqm", status: "asking", date: "Sep 2026", price_ngn: 620_000_000, days_listed: 25, source: "PropertyPro asking" },
    { label: "A4", description: "4-bed detached, 450 sqm", status: "asking", date: "Apr 2026", price_ngn: 600_000_000, adjustments_pct: 7, adjustment_note: "bedroom", days_listed: 170, source: "NPC asking" },
  ],
  list_to_close_discount_pct: -8,
  track_record: { at_market_close_vs_list_pct: -3, at_market_dom: 52, at_market_n: 6, above_market_close_vs_list_pct: -12, above_market_dom: 88, above_market_n: 5 },
  heat: {
    nominal_price_change_pct: 12,
    cpi_yoy_pct: 15,
    dom_now: 64,
    dom_year_ago: 58,
    listings_now: 41,
    listings_year_ago: 34,
    inquiries_change_pct: 18,
    rent_change_nominal_pct: 22,
  },
  fx_ngn_per_usd: 1500,
  segment_mix_pct: { local: 55, diaspora: 30, investor: 15 },
  funnel_rates: { inquiry_to_qualified: 0.25, qualified_to_viewing: 0.35, viewing_to_offer: 0.15, offer_to_close: 0.5 },
  cost_per_qualified_lead_ngn: 65_000,
  production_cost_ngn: 1_800_000,
  events_cost_ngn: 500_000,
  commission_rate_pct: 5,
  budget_cap_ngn: 6_000_000,
  launch_date: "2026-10-12",
  target_close_days: 90,
  lease_fallback_rent_ngn_per_year: 30_000_000,
  presenter: "Marketing Strategist",
};

/** Mirrors real-estate-exec-brief/examples/output-market-brief.md (fictional figures). */
export const IK203: MarketBriefInput = {
  asset: { id: "IK-203", district: "Ikoyi", type: "flat", bedrooms: 3, built_sqm: 210, title: "registered_deed", status: "vacant" },
  comps: [
    { label: "C1", description: "3-bed flat, 210 sqm", status: "closed", date: "Jul 2026", price_ngn: 400_000_000, source: "Closed: internal" },
    { label: "C2", description: "3-bed flat, 205 sqm", status: "closed", date: "Apr 2026", price_ngn: 370_000_000, adjustments_pct: 3, adjustment_note: "dated finish", source: "Closed: internal" },
    { label: "C3", description: "3-bed flat, 190 sqm", status: "closed", date: "Jan 2026", price_ngn: 385_000_000, adjustments_pct: 5, adjustment_note: "smaller", source: "Closed: agent-reported" },
    { label: "A1", description: "3-bed flat, 215 sqm, newer block", status: "asking", date: "Aug 2026", price_ngn: 450_000_000, adjustments_pct: -5, adjustment_note: "newer building", source: "NPC asking" },
    { label: "A2", description: "3-bed flat, 210 sqm", status: "asking", date: "Sep 2026", price_ngn: 420_000_000, source: "PropertyPro asking" },
  ],
  list_to_close_discount_pct: -8,
  heat: {
    nominal_price_change_pct: 10,
    cpi_yoy_pct: 15,
    dom_now: 75,
    dom_year_ago: 62.5,
    listings_now: 54,
    listings_year_ago: 50,
    inquiries_change_pct: -5,
    rent_change_nominal_pct: 21,
  },
  rent_estimate_ngn_per_year: 32_000_000,
  segment_median_gross_yield_pct: 6.5,
  service_charge_ngn_per_year: 4_500_000,
  maintenance_ngn_per_year: 1_200_000,
  vacancy_months: 1,
  hurdle_rate_pct: 15,
  as_of_date: "2026-10-03",
  review_date: "2027-03-31",
};
